//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RL_Map_Loader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstTimeRun {
            get {
                return ((bool)(this["IsFirstTimeRun"]));
            }
            set {
                this["IsFirstTimeRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Steam\\steamapps\\common\\rocketleague")]
        public string RocketLeagueInstallDirectory {
            get {
                return ((string)(this["RocketLeagueInstallDirectory"]));
            }
            set {
                this["RocketLeagueInstallDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Steam\\steamapps\\common\\rocketleague\\Binaries\\RocketLeague.exe")]
        public string RocketLeagueExecutableFilepath {
            get {
                return ((string)(this["RocketLeagueExecutableFilepath"]));
            }
            set {
                this["RocketLeagueExecutableFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SteamLibrary\\steamapps\\common\\rocketleague\\Binaries\\Win64\\bakkesmod")]
        public string BakkesModDataDirectory {
            get {
                return ((string)(this["BakkesModDataDirectory"]));
            }
            set {
                this["BakkesModDataDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\LogMeIn Hamachi")]
        public string HamachiDirectory {
            get {
                return ((string)(this["HamachiDirectory"]));
            }
            set {
                this["HamachiDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\BakkesMod\\BakkesMod.exe")]
        public string BakkesModExecutableFilepath {
            get {
                return ((string)(this["BakkesModExecutableFilepath"]));
            }
            set {
                this["BakkesModExecutableFilepath"] = value;
            }
        }
    }
}
